<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function usajobs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'usajobs.help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help docs for USAjobs, see <a href="!usajobs-module">the online documentation</a></p>');
      return $output;
    break;
  }
}

/**
 * Implements hook_theme().
 */
function usajobs_theme($existing, $type, $theme, $path) {
  //add jobs variable and assign twig template for the block template
  return array(
    'usajobs_block' =>
      array(
        'variables' => array(
          'jobs' => NULL,
        ),
        'template' => 'block--usajobs-block',
      )
  );
}
