usajobs_integration.settings:
  type: config_object
  label: 'USAjobs Integration Settings'
  mapping:
    user_agent:
      type: email
      label: 'User Agent'
    api_key:
      type: string
      label: 'API Key'
    endpoint_url:
      type: string
      label: 'Search API URL'
    host:
      type: string
      label: 'Host'

usajobs_integration.parameters:
  type: config_object
  label: 'USAjobs Search API Request Parameters'
  mapping:
    Organization:
      type: string
      label: 'Organization'
    Keyword:
      type: string
      label: 'Keyword'
    KeywordExclusion:
      type: string
      label: 'Keyword Exclusion'
    KeywordFilter:
      type: string
      label: 'Keyword Filter'
    PositionTitle:
      type: string
      label: 'Position Title'
    RemunerationMinimumAmount:
      type: float
      label: 'Minimum Salary'
    RemunerationMaximumAmount:
      type: float
      label: 'Maximum Salary'
    JobGradeCode:
      type: string
      label: 'Pay Plan'
    PayGradeHigh:
      type: string
      label: 'Maximum Pay Grade'
    PayGradeLow:
      type: string
      label: 'Minimum Pay Grade'
    JobCategoryCode:
      type: string
      label: 'Job Category Code'
    LocationName:
      type: string
      label: 'Location Name'
    Radius:
      type: integer
      label: 'Radius'
    PositionOfferingTypeCode:
      type: sequence
      label: 'Position Offering Type Code'
      sequence:
        type: string
    TravelPercentage:
      type: string
      label: 'Travel Percentage'
    PositionScheduleTypeCode:
      type: sequence
      label: 'Position Schedule Type Code'
      sequence:
        type: integer
    RelocationIndicator:
      type: boolean
      label: 'Relocation Indicator'
    SecurityClearanceRequired:
      type: sequence
      label: 'Security Clearance Code'
      sequence:
        type: integer
    SupervisoryStatus:
      type: boolean
      label: 'Supervisory Status'
    DatePosted:
      type: string
      label: 'Date Posted'
    WhoMayApply:
      type: string
      label: 'Who May Apply'
    Fields:
      type: string
      label: 'Fields'
    SES:
      type: boolean
      label: 'Senior Executive Service'
    Student:
      type: boolean
      label: 'Student'
    Internship:
      type: boolean
      label: 'Internship'
    RecentGrad:
      type: boolean
      label: 'Student'
